### ISSUE TITLE
NMEA2000.SetCANPort("can0");

### ISSUE THREAD

**Issue by ben22ee** [thomasonw/NMEA2000_socketCAN#1]
I have a raspberry pi 2 with pican2 duo iso board.  I am trying to display NMEA2000 traffic using the sample main.cpp code here:  https://github.com/thomasonw/NMEA2000_socketCAN.  I am using NetBeans IDE 8.2 and have both NMEA2000_socketCAN and NMEA2000 in my build.  When I try to compile the sample code, I get the following compile error:

main.cpp: In function ‘int main()’:
main.cpp:25:14: error: ‘class tNMEA2000’ has no member named ‘SetCANPort’
     NMEA2000.SetCANPort("can0");                                                // Select the CAN port @ can0 (default)

If I comment out the "NMEA2000.SetCANPort"can0");" it will compile and run, but I'm not seeing data when connected to a NMEA2000 network.  I have run candump (can0) and cansend (can1) and it works.

Any ideas on how to correct this issue?  Is there code to detect and display the the bitrate of a device on the network?

**Comment by thomasonw** [comment]
Hello - and sorry you are having issues with this.

Tonight I did a test and am able to reproduce the compile issue, however it works well using a down-rev release of the NMEA2000 lib.  The latest release of the lib may well be related to the other problem you are having as well.

Timo does not provide version archives of his lib, but I do happen to have a clone of a version from about a year ago here: [ https://github.com/thomasonw/NMEA2000]( https://github.com/thomasonw/NMEA2000)   It does compile with no errors, perhaps you can use it for now and see if you are able to make some progress until I can resolve why this bridge will not work with the latest version of the NEMA2000 lib.

**Comment by ben22ee** [comment]
First, thank you for sharing your work and for helping me with the issue.  I very much appreciate the work you and Timo have done.  I added the NMEA2000 clone you posted and I get it to compile and run now.  I will test it this weekend with a NMEA2000 source.  I noticed some differences in NMEA2000_CAN.h which include:  

line 95 was: tNMEA2000_SocketCAN NMEA2000;
line 98 now in latest version:  tNMEA2000 &NMEA2000=*(new tNMEA2000_SocketCAN());

line 140 was:  tNMEA2000_mcp NMEA2000(N2k_SPI_CS_PIN,MCP_CAN_CLOCK_SET,N2k_CAN_INT_PIN,MCP_CAN_RX_BUFFER_SIZE);
line 143 now in latest version:  tNMEA2000 &NMEA2000=*(new tNMEA2000_mcp(N2k_SPI_CS_PIN,MCP_CAN_CLOCK_SET,N2k_CAN_INT_PIN,MCP_CAN_RX_BUFFER_SIZE));

Although it compiles and runs, I'm wondering if maybe the CS and INT pins are not correctly defined as I'm not seeing anything in the code with these numbers for the pican2 duo iso on a raspberry 2:
Header Pin ; GPIO ; Description	               
35	                  ; 24	      ;  PCM_FS/PWM1	        
37	                 ;  25	      ;  GPIO 25	                         
16	                ; 4	     ;  Can A LED (not used)	 
32	                ; 26	     ;  Can B (not used)	         

I added this to the end of the /boot/config.txt file per the setup instructions so perhaps this is enough:
dtparam=spi=on
dtoverlay=mcp2515-can0,oscillator=16000000,interrupt=25
dtoverlay=mcp2515-can1,oscillator=16000000,interrupt=24
dtoverlay=spi-bcm2835-overlay

I will test it this weekend and report back.  Thank you for your time and help.

**Comment by ben22ee** [comment]
Looks like I have at least a couple of issues with the Pi 2 and Pican2 Duo Isolated board.

I tried the new build but it did not work.  The display would say it was watching...but no data.

I moved the cable from "CanA" to "CanB" and I was still not able to see data with the new build.  I pulled up candump and also Wireshark and saw data transmitting.   The code identifies the ports as can0 and can1.  The Pican2 duo iso board has the ports labeled CanA and CanB.  I assumed that can0=CanA and Can1=CanB but that was not the case, it is actually the opposite.

I emailed Copperhills Technologies to see if I can get a schematic of the Pican2 Duo Iso board to verify the pinouts.  They have schematics for their other boards online, but not for this particular board (http://copperhilltech.com/pican2-duo-isolated-can-bus-board-for-raspberry-pi-2-3/).  It doesn't appear the code is getting data from the Pican board.  If there is some debug code I can try, please let me know.

**Comment by thomasonw** [comment]
Myself, I find `candump`  helpful to make sure the underlying hardware and Linux drivers are working.

**Comment by ttlappalainen** [comment]
Note that NMEA2000_CAN.h is meant for simple automatic selection right underlying CAN object. The line 98 you refer changes only the object type to tNMEA2000 instead of tNMEA2000_SocketCAN. The reason for change was simple, now it is possible to use NMEA2000 object in different modules by adding reference:
`extern tNMEA2000 &NMEA2000;`
If you know the platform you are using, instead of including NMEA2000_CAN.h you include:
`#include <NMEA2000_SocketCAN.h>`
and then you define you object
`tNMEA2000_SocketCAN NMEA2000;`
With this way the call
`NMEA2000.SetCANPort("can0");`
will compile right.

I also prefer to improve tNMEA2000_SocketCAN class so that it can take port in constructor:
`tNMEA2000_SocketCAN::tNMEA2000_SocketCAN(const char *port=0);`
In this way we can still use automatic object selection by using definition as for other object. So then you could use:
```
#define SOCKET_CAN_PORT "can1"
#include "NMEA2000_CAN.h"

```and on NMEA2000_CAN.h around line 98 you would have code
```
#ifndef SOCKET_CAN_PORT
#define SOCKET_CAN_PORT 0
 tNMEA2000 &NMEA2000=*(new tNMEA2000_SocketCAN(SOCKET_CAN_PORT));
```
Then you would not need `NMEA2000.SetCANPort("can0");` in your code and it it should directly compile e.g. for Teensy too.

I also prefer to change
```
int skt;
char _CANport[50] = "can0";                                                     // Default to can0 if user does not set it.
```
as class members instead of globals. In this way it would be possible to have tw NMEA2000 object in the system e.g. for gateway devices.

Thomas: Will you do above fixes and test them, since I do not yet have working RPi environment for testing? Also test against latest library, since that all last developments and requirements.

**Comment by thomasonw** [comment]
@ttlappalainen :  Thank you for chipping in.  C++ is not my strong area, and I appreciate any help I can get!  Today I was able to get to my RPi and do some debugging on hardware and have found the major issue:  Expression evaluation of cascaded contritions.  The line I found (there may be more like this) was contained in `NMEA2000.cpp`, line 836:
` DeviceReady = (dbMode!=dm_None) || CANOpen();`

The RPi compiler appears to properly implement 'Minimal Evaluation', and in the case of line 836: once `dbMode!=dm_None` evaluates as TRUE, the 2nd condition will not be exercised.  My example called `   NMEA2000.SetDebugMode(tNMEA2000::dm_ClearText); `   As such the 1st test resolves true (!=dm_None) and  `CANOpen()` is never called.

[https://en.wikipedia.org/wiki/Short-circuit_evaluation#Common_use](https://en.wikipedia.org/wiki/Short-circuit_evaluation#Common_use)

There may be more such serial conditional statements, I have not checked for them. 

I have also done some modes in the NMEA2000_socket code to align more with your programming style.  I am still working to create it so that the string name can be defined either a compile time (as shown above), or allowed to be determined at runtime.    Specifically in the case of where an application may need to preform some run-time sampling, or even prompt the user, to select the CAN socket source.  The prior approach allowed a call to `NMEA2000.SetCANPort(CANName);` before calling open() and seemed clean.   The way I have it now, to allow for the same functionality, is the constructor accepts a pointer to a string.  This allows one to create the constructor and pass in the CANName array, which is at a later time fulled with the actual string of the socket to be used.  (NULL or missing in the constructor set the pointer to a default `can0` string).  Still works, but seems a little disconnected having run-time as well as  (as opposed to compile time) values sent in at the constructor, as well as the odd #defines.   Still working to see if I can clean it up.

I still have to do some cleanup on the NMEA2000_socket code, and am not able to proof it on a real RPi for a few more days until I return to the boat.  Perhaps in the mean time you can look into the Short-circuit evaluations in the NEMA2000 code?

**Comment by ttlappalainen** [comment]
The code `DeviceReady = (dbMode!=dm_None) || CANOpen();` works as it has been designed. On debug mode it should not open CAN at all. In debug mode CAN read/writes should no be called so you can test your code without true bus, since some CAN libraries gets stuck, if CAN has not been connectd. If you like to get clear text output from the library, you have to set:
```
  Serial.begin(115200);
  NMEA2000.SetForwardStream(&Serial);  // PC output on due programming port
  NMEA2000.SetForwardType(tNMEA2000::fwdt_Text); // Show in clear text. Leave uncommented for default Actisense format.
```
Since Serial is Arduino depended, on linux system you have to use class inherited from N2kStream.

The idea of using NMEA2000_CAN.h is that it makes it simple to move your code between different boards. If you are anyway using platform dependent code in you your code, there is no sense to use that and instead then just have:
`#include <NMEA2000_SocketCAN.h>`
and then you define you object
`tNMEA2000_SocketCAN NMEA2000;`

**Comment by thomasonw** [comment]
@ttlappalainen :  OK, I was not aware that enabling Debug messages disabled the CAN low level drivers.  Explains why the example stopped working in this past year!

See updates to both the socketCAN lib, and NMEA2000 lib to support auto-selection of socketCAN on Linux systems.  Includes your suggestions for moving port selection from API extension to constructor #defines, with examples allowing for alternative port selection at compile time as well as run-time.

Thank you both for bring this issue up, and providing insight to helping to resolve it.  I will leave this issue OPEN for a few more days to allow folks time to test out the changes and confirm if they see any issues or not.

**Comment by ben22ee** [comment]
Thank you both for the suggestions and updates.

I compiled the new files successfully after reparsing to eliminate "Unable to resolve identifier" errors.  I will test this weekend with my Pi2.

**Comment by ttlappalainen** [comment]
NMEA2000 library NMEA2000_CAN.h is now also updated with thomasow modifications. Please try to use the latest library, since that contains all currently known required features for bus devices.

**Comment by ben22ee** [comment]
I'm seeing data now with the updates and latest library.  Thank you.

Will the example show all pgn traffic on the network (including proprietary messages)?

**Comment by ttlappalainen** [comment]
See my response on https://github.com/ttlappalainen/NMEA2000/issues/101#issuecomment-366567346

**Comment by thomasonw** [comment]
All,   Thank you for bringing this up, providing guidance, and confirming the solution!  Will close now.
